### ISSUE TITLE
This repo is marked as excluded project. Hacktoberfest

### ISSUE THREAD

**Issue by saran-surya** [TusharKukra/Hacktoberfest2021-EXCLUDED#305]
Hi @TusharKukra ,
I am getting a notification that the current repo is being excluded from the hacktoberfest. Kindly clarify us regarding it.

![image](https://user-images.githubusercontent.com/59312489/135756187-be72a57a-e705-483b-a45c-4e5770548532.png)

Thanks.

**Comment by itsnitish22** [comment]
Yeah, it got excluded :(

**Comment by saran-surya** [comment]
> Yeah, it got excluded :(

Yep, So if they can at least mark it in the readme as people can get to know it in the first hand.

**Comment by itsnitish22** [comment]
Ya you're right. And I believe hacktoberfest is labelling dsa repos as spam that's why it got excluded.
So we should contribute to the repos other than dsa from now onwards.

**Comment by saran-surya** [comment]
> Ya you're right. And I believe hacktoberfest is labelling dsa repos as spam that's why it got excluded. So we should contribute to the repos other than dsa from now onwards.

Yep, that is what  I also think so.

**Comment by TusharKukra** [comment]
If u still want to add more PRs then use my New Repo LearnReact
